apiVersion: v1
kind: Pod
metadata: 
  name: myhttp
  labels: 
    app: myapp
    env: devops
spec:
  containers:
    - name: http
      image: httpd
      ports:
        - name: http-port
          containerPort: 80