apiVersion: v1
kind: Pod
metadata: 
  name: myhttp
  labels: 
    app: myapp
    env: devops
spec:
  containers:
    - name: http
      image: httpd
      ports:
        - name: http-port
          containerPort: 80
---


apiVersion: v1
kind: Service
metadata: 
  name: myhttp-svc
spec: 
  type: NordPort
  selector:
    app: myapp
ports:
- port: 80
  targetPort: 81

                   
    